- name: Configurar Bastion_Host_P
  hosts: Bastion_Host_P
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Configurar hostname
      cisco.ios.ios_config:
        lines:
          - hostname Bastion_Host_P

    - name: Configurar interfaz g0/1
      cisco.ios.ios_config:
        lines:
          - ip address 10.0.0.10 255.0.0.0
          - no shutdown
          - no ip routing
          - ip default-gateway 10.0.0.1
        parents: interface GigabitEthernet0/1


