- name: Configuración completa de la topología
  hosts: all
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Configurar Router_P
      when: "'router_p' in group_names"
      block:
        - name: Configurar hostname
          cisco.ios.ios_config:
            lines:
              - hostname Router_P

        - name: Configurar interfaz g0/1
          cisco.ios.ios_config:
            lines:
              - description Router_P -> PC
              - ip address 10.0.0.1 255.0.0.0
              - no shutdown
            parents: interface GigabitEthernet0/1

        - name: Configurar interfaz g0/2
          cisco.ios.ios_config:
            lines:
              - description Router_P -> RBB
              - ip address 20.0.0.1 255.0.0.0
              - no shutdown
            parents: interface GigabitEthernet0/2

        - name: Configurar ACL para permitir Telnet y bloquear ICMP desde Bastion_P hacia RBB
          cisco.ios.ios_config:
            lines:
              - ip access-list extended ACL_Bastion_to_RBB
              - permit tcp host 10.0.0.10 host 30.0.0.2 eq 23
              - deny icmp host 10.0.0.10 host 30.0.0.2
              - permit ip any any
            save_when: modified

        - name: Aplicar ACL en interfaz hacia Bastion_P
          cisco.ios.ios_config:
            lines:
              - ip access-group ACL_Bastion_to_RBB in
            parents: interface GigabitEthernet0/1

    - name: Configurar RBB
      when: "'rbb' in group_names"
      block:
        - name: Configurar hostname
          cisco.ios.ios_config:
            lines:
              - hostname RBB

        - name: Configurar interfaz g0/1
          cisco.ios.ios_config:
            lines:
              - description RBB -> Router_P
              - ip address 30.0.0.2 255.0.0.0
              - no shutdown
            parents: interface GigabitEthernet0/1

        - name: Configurar VTY para Telnet
          cisco.ios.ios_config:
            lines:
              - password cisco
              - login
              - transport input telnet
            parents: line vty 0 4

    - name: Configurar Bastion_P
      when: "'bastion_p' in group_names"
      block:
        - name: Configurar hostname
          cisco.ios.ios_config:
            lines:
              - hostname Bastion_P

        - name: Configurar interfaz g0/1
          cisco.ios.ios_config:
            lines:
              - ip address 10.0.0.10 255.0.0.0
              - no shutdown
              - no ip routing
              - ip default-gateway 10.0.0.1
            parents: interface GigabitEthernet0/1
