- name: Configurar RBB para permitir Telnet y bloquear ICMP
  hosts: RBB
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: cisco
    ansible_password: class
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: class

  tasks:
    - name: Configuración de interfaz G0/1
      cisco.ios.ios_config:
        lines:
          - ip address 20.0.0.2 255.0.0.0
          - description RBB->ROUTER_P
          - no shutdown
        parents: interface GigabitEthernet0/1

    - name: Configuración de usuario para SSH
      cisco.ios.ios_config:
        lines:
          - username cisco privilege 15 secret class

    - name: Configuración de Telnet y SSH en líneas VTY
      cisco.ios.ios_config:
        lines:
          - login local
          - transport input telnet ssh
          - password cisco   # se usa solo para Telnet
        parents: line vty 0 4

    - name: Configuración de ruta estática hacia red 10.0.0.0/24
      cisco.ios.ios_config:
        lines:
          - ip route 10.0.0.0 255.255.255.0 20.0.0.1

